name: Go CI/CD

on:
  push:

jobs:
  build:
    name: Go CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Check formatting
        run: |
          make check-fmt
      - name: Get dependencies
        run: |
          make depends
      - name: Build
        run: |
          make build
      - name: Test
        run: |
          make check
