name: Go CI/CD

on:
  push:

env:
  GOSEC_VERSION: "2.16.0"

jobs:
  build:
    name: Go CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Install gosec
        run: |
          mkdir -p "${HOME}/.local/bin"
          curl -sL "https://github.com/securego/gosec/releases/download/v${GOSEC_VERSION}/gosec_${GOSEC_VERSION}_linux_amd64.tar.gz" | tar xzf - -C "${HOME}/.local/bin" gosec
      - name: Check formatting
        run: |
          make check-fmt
      - name: Check code via gosec
        run: |
          make gosec
      - name: Get dependencies
        run: |
          make depends
      - name: Build
        run: |
          make build
      - name: Test
        run: |
          make check
